env: "local"

logger:
  level: "debug"

service:
  name: "bookstores-api"
  host: "0.0.0.0"
  port: "8080"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  db_name: "bookstores"
  ssl_mode: "disable"
  max_conns: 10
